# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tyler/Computer-Automation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tyler/Computer-Automation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@echo "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@echo "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@echo "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@echo "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@echo "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@echo "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tyler/Computer-Automation/CMakeFiles /home/tyler/Computer-Automation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tyler/Computer-Automation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Computer-Automation

# Build rule for target.
Computer-Automation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Computer-Automation
.PHONY : Computer-Automation

# fast build rule for target.
Computer-Automation/fast:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/build
.PHONY : Computer-Automation/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/main.c.s
.PHONY : main.c.s

src/Win32.o: src/Win32.c.o

.PHONY : src/Win32.o

# target to build an object file
src/Win32.c.o:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/Win32.c.o
.PHONY : src/Win32.c.o

src/Win32.i: src/Win32.c.i

.PHONY : src/Win32.i

# target to preprocess a source file
src/Win32.c.i:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/Win32.c.i
.PHONY : src/Win32.c.i

src/Win32.s: src/Win32.c.s

.PHONY : src/Win32.s

# target to generate assembly for a file
src/Win32.c.s:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/Win32.c.s
.PHONY : src/Win32.c.s

src/scanner.o: src/scanner.c.o

.PHONY : src/scanner.o

# target to build an object file
src/scanner.c.o:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/scanner.c.o
.PHONY : src/scanner.c.o

src/scanner.i: src/scanner.c.i

.PHONY : src/scanner.i

# target to preprocess a source file
src/scanner.c.i:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/scanner.c.i
.PHONY : src/scanner.c.i

src/scanner.s: src/scanner.c.s

.PHONY : src/scanner.s

# target to generate assembly for a file
src/scanner.c.s:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/scanner.c.s
.PHONY : src/scanner.c.s

src/script.o: src/script.c.o

.PHONY : src/script.o

# target to build an object file
src/script.c.o:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/script.c.o
.PHONY : src/script.c.o

src/script.i: src/script.c.i

.PHONY : src/script.i

# target to preprocess a source file
src/script.c.i:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/script.c.i
.PHONY : src/script.c.i

src/script.s: src/script.c.s

.PHONY : src/script.s

# target to generate assembly for a file
src/script.c.s:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/script.c.s
.PHONY : src/script.c.s

src/x11.o: src/x11.c.o

.PHONY : src/x11.o

# target to build an object file
src/x11.c.o:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/x11.c.o
.PHONY : src/x11.c.o

src/x11.i: src/x11.c.i

.PHONY : src/x11.i

# target to preprocess a source file
src/x11.c.i:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/x11.c.i
.PHONY : src/x11.c.i

src/x11.s: src/x11.c.s

.PHONY : src/x11.s

# target to generate assembly for a file
src/x11.c.s:
	$(MAKE) -f CMakeFiles/Computer-Automation.dir/build.make CMakeFiles/Computer-Automation.dir/src/x11.c.s
.PHONY : src/x11.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Computer-Automation"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Win32.o"
	@echo "... src/Win32.i"
	@echo "... src/Win32.s"
	@echo "... src/scanner.o"
	@echo "... src/scanner.i"
	@echo "... src/scanner.s"
	@echo "... src/script.o"
	@echo "... src/script.i"
	@echo "... src/script.s"
	@echo "... src/x11.o"
	@echo "... src/x11.i"
	@echo "... src/x11.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

